name: CI
on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Compile with PyInstaller
      run: |
        pyinstaller --onefile main.py

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: main-${{ matrix.os }}
        path: dist/main${{ runner.os == 'Windows' && '.exe' || '' }}